/* tslint:disable */
export const memory: WebAssembly.Memory;
export function __wbindgen_global_argument_ptr(): number;
export function create(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function __wbindgen_describe_create(): void;
export function __wbindgen_describe___wbg_info_621deeff391879ff(): void;
export function __wbg_proxy_free(a: number): void;
export function proxy_get_move_names(a: number): number;
export function __wbindgen_describe_proxy_get_move_names(): void;
export function proxy_get_state(a: number): number;
export function proxy_get_player_id(a: number): number;
export function __wbindgen_describe_proxy_get_player_id(): void;
export function proxy_dispatch(a: number, b: number): void;
export function __wbindgen_describe_proxy_dispatch(): void;
export function __wbindgen_describe_proxy_get_state(): void;
export function __wbindgen_describe___wbg_error_f7214ae7db04600c(): void;
export function __wbindgen_describe___wbg_new_a99726b0abef495b(): void;
export function __wbindgen_describe___wbg_stack_4931b18709aff089(): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_free(a: number, b: number): void;
