/* tslint:disable */
export const memory: WebAssembly.Memory;
export function __wbindgen_global_argument_ptr(): number;
export function create(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function __wbindgen_describe_create(): void;
export function __wbindgen_describe___wbg_new_886f15c1b20b061b(): void;
export function __wbindgen_describe___wbg_call_a2b503e0ee1234e4(): void;
export function __wbindgen_describe___wbg_crypto_4b7669ff1793d881(): void;
export function __wbindgen_describe___wbg_getRandomValues_95cef5eed1acafda(): void;
export function __wbindgen_describe___wbg_randomFillSync_571502126f344d60(): void;
export function __wbindgen_describe___wbg_self_ddd2d80076091e5f(): void;
export function __wbindgen_describe___wbg_getRandomValues_6de85818bd2ad699(): void;
export function __wbindgen_describe___wbg_require_86edd37cfda5f13d(): void;
export function __wbindgen_describe___wbg_info_621deeff391879ff(): void;
export function __wbg_proxy_free(a: number): void;
export function proxy_get_move_names(a: number): number;
export function __wbindgen_describe_proxy_get_move_names(): void;
export function proxy_get_state(a: number): number;
export function proxy_get_player_id(a: number): number;
export function __wbindgen_describe_proxy_get_player_id(): void;
export function proxy_dispatch(a: number, b: number): void;
export function __wbindgen_describe_proxy_dispatch(): void;
export function __wbindgen_describe_proxy_get_state(): void;
export function __wbindgen_describe___wbg_error_f7214ae7db04600c(): void;
export function __wbindgen_describe___wbg_new_a99726b0abef495b(): void;
export function __wbindgen_describe___wbg_stack_4931b18709aff089(): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_free(a: number, b: number): void;
